documentation:
  - changed-files:
    - any-glob-to-any-file: 'docs/*'
    - any-glob-to-any-file: 'docs/**/*'
    - any-glob-to-any-file: 'mkdocs.yml'

github-actions:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/*'
      - any-glob-to-any-file: '.github/workflows/**/*'
      - any-glob-to-any-file: '.github/dependabot.yml'
      - any-glob-to-any-file: '.github/boring-cyborg.yml'
      - any-glob-to-any-file: '..github/release-drafter.yml'
      - any-glob-to-any-file: '.github/semantic.yml'
      - any-glob-to-any-file: '.github/stale.yml'
      - any-glob-to-any-file: '.github/mergify.yml'
      - any-glob-to-any-file: '.github/labeler.yml'

github-templates:
  - changed-files:
      - any-glob-to-any-file: '.github/ISSUE_TEMPLATE/*'
      - any-glob-to-any-file: '.github/PULL_REQUEST_TEMPLATE.md'
      - any-glob-to-any-file: '.github/.chglog/*'
      - any-glob-to-any-file: '.github/.chglog/**/*'

internal:
  - changed-files:
      - any-glob-to-any-file: '.flake8'
      - any-glob-to-any-file: '.bandit.baseline'
      - any-glob-to-any-file: '.gitignore'
      - any-glob-to-any-file: '.pre-commit-config.yaml'
      - any-glob-to-any-file: 'MANIFEST.in'
      - any-glob-to-any-file: 'Makefile'
      - any-glob-to-any-file: 'CONTRIBUTING.md'
      - any-glob-to-any-file: 'MAINTAINERS.md'
      - any-glob-to-any-file: 'CODE_OF_CONDUCT.md'
      - any-glob-to-any-file: 'LICENSE'
      - any-glob-to-any-file: 'THIRD-PARTY-LICENSES'
      - any-glob-to-any-file: '.dockerignore'
      - any-glob-to-any-file: '.editorconfig'
      - any-glob-to-any-file: 'setup.cfg'

dependencies:
  - changed-files:
      - any-glob-to-any-file: 'pyproject.toml'
      - any-glob-to-any-file: 'poetry.lock'
      - any-glob-to-any-file: 'requirements.txt'

tests:
  - changed-files:
      - any-glob-to-any-file: 'automated_tests/*'
      - any-glob-to-any-file: 'automated_tests/**/*'
      - any-glob-to-any-file: 'tests/*'
      - any-glob-to-any-file: 'tests/**/*'

build:
  - changed-files:
        - any-glob-to-any-file: 'Dockerfile'
        - any-glob-to-any-file: 'Dockerfile.*'
        - any-glob-to-any-file: 'docker-compose.yml'
        - any-glob-to-any-file: 'docker-compose.*.yml'
        - any-glob-to-any-file: 'docker-compose.*.yaml'
        - any-glob-to-any-file: 'docker-compose.*.yaml'
        - any-glob-to-any-file: 'docker-compose'

golang:
  - changed-files:
      - any-glob-to-any-file: 'go.mod'
      - any-glob-to-any-file: 'go.sum'
      - any-glob-to-any-file: '**/*.go'

javascript:
  - changed-files:
      - any-glob-to-any-file: '**/*.json'

json:
  - changed-files:
      - any-glob-to-any-file: '**/*.json'

markdown:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

python:
  - changed-files:
      - any-glob-to-any-file: 'requirements.txt'
      - any-glob-to-any-file: '**/*.py'

sql:
  - changed-files:
      - any-glob-to-any-file: '**/*.sql'

typescript:
  - changed-files:
      - any-glob-to-any-file: '**/*.ts'
      - any-glob-to-any-file: '**/*.tsx'
